package com.qyuesuo.servlet;

import com.qyuesuo.utils.JDBCUtil;

import java.sql.*;

public class DerbyTest {
    public static void main(String[] args) {
      ResultSet resultSet =null;
        try {
            Statement statement = JDBCUtil.getStatement();
            statement.execute("create table t_file3(id int generated by default as identity primary key,oldName varchar(200) not null,newName varchar(200) not null,ext varchar(50) not null,path varchar(200) not null ,size varchar(50) not null,uploadTime timestamp default current_timestamp  )");
            statement.executeUpdate("insert into t_file3(oldName,newName,ext,path,size)VALUES('old','new','txt','D:\\\\file',\n" +
                    "'512k')");
            statement.executeUpdate("insert into t_file3(oldName,newName,ext,path,size)VALUES('old','new1','doc','D:\\\\file',\n" +
                    "'1024k')");
           resultSet = statement.executeQuery("select * from t_file3 ORDER BY uploadTime DESC");
            while (resultSet.next()) {
                String newName = resultSet.getString("newName");
                String uploadTime = resultSet.getString("uploadTime");
                String id = resultSet.getString("id");
                System.out.println(newName + "======>" + uploadTime+ "======>" +id);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            JDBCUtil.close(resultSet);
        }

    }
}
