package com.qyuesuo.utils;

import java.sql.*;

public class JDBCUtil {

    static Connection con = null;
    static  Statement statement=null;
     static {
        try {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            con = DriverManager.getConnection("jdbc:derby:vsjdb;create=true");
            statement = con.createStatement();
            Statement statement1 = getStatement();
            statement1.execute("create table t_file(id int generated by default as identity primary key,oldName varchar(200) not null,newName varchar(200) not null,ext varchar(50) not null,path varchar(200) not null ,size varchar(50) not null,uploadTime timestamp default current_timestamp  )");
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } finally {
            close();
        }
    }

    public static Statement getStatement() {
        try {
            con = DriverManager.getConnection("jdbc:derby:vsjdb;create=true");
            statement = con.createStatement();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return statement;
    }

    public static void close(){
        try {
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        try {
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void close( ResultSet resultSet){
        try {
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        try {
            resultSet.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        try {
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }


}
