package com.qyuesuo.utils;

import java.sql.*;

public class JDBCUtil {

    static Connection con = null;
    static Statement statement = null;
    static Boolean flag = true;

    private static void createTable() {
        try {

            flag = true;
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            con = DriverManager.getConnection("jdbc:derby:vsjdb;create=true");
            statement = con.createStatement();
            statement.execute("create table t_file(id int generated by default as identity primary key,oldName varchar(200) not null,newName varchar(200) not null,ext varchar(50) not null,path varchar(200) not null ,size varchar(50) not null,digitalEnvelope varchar (256) not null ,uploadTime timestamp default current_timestamp  )");
            statement.close();
            con.close();
        } catch (Exception e) {

        } finally {
            try {
                if(statement!=null){
                    statement.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            try {
                if(con!=null){
                    con.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }


    public static Statement getStatement() {
        if (flag) {
            createTable();
        }
        try {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            con = DriverManager.getConnection("jdbc:derby:vsjdb;create=true");
            statement = con.createStatement();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        return statement;
    }

    public static void close() {
        try {
            if (statement != null) {
                statement.close();
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        try {
            if (con != null) {
                con.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void close(ResultSet resultSet) {
        try {
            if(statement!=null){
                statement.close();
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        try {
            if(resultSet!=null){
                resultSet.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        try {
            if(con!=null){
                con.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }


}
